name: PR Checklist

on:
  issue_comment:
    types:
      - created

jobs:
  pr_checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Check for PR submit comment
        id: pr_comment
        run: |
          echo "::set-output name=pr_comment::$(jq -r .comment.body $GITHUB_EVENT_PATH)"
        shell: bash

      - name: Check PR Checklist
        run: |
          pr_comment="$PR_COMMENT"
          # 여기에 PR submit comment에 대한 체크리스트를 파싱하고 수행하는 로직을 추가합니다.
          # 예를 들어, PR submit comment에서 특정 키워드를 검색하거나 정규식을 사용하여 체크리스트 항목을 추출합니다.
          # 체크리스트 항목을 추출한 후, 필요한 작업을 수행하고 결과를 출력합니다.
          # 결과를 이용하여 해당 PR에 comment를 남길 수 있습니다.
        shell: bash
